name: chat_mobile
version: 0.1.0
description: Mobile UI for Chat multi-LLM interface.
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  http: ^1.2.1
  flutter_markdown: ^0.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
